# Generated by Django 6.0.6 on 2026-07-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Examination",
            fields=[
                (
                    "exam_id",
                    models.IntegerField(blank=True, primary_key=True, serialize=False),
                ),
                ("exam_title", models.CharField(max_length=255, unique=True)),
                ("subject", models.CharField(max_length=255)),
                ("duration", models.IntegerField()),
                ("total_marks", models.IntegerField()),
                ("exam_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="ExamSubmission",
            fields=[
                (
                    "submission_id",
                    models.IntegerField(blank=True, primary_key=True, serialize=False),
                ),
                ("student_name", models.CharField(max_length=255)),
                ("exam_title", models.CharField(max_length=255)),
                ("submitted_answers", models.TextField()),
                ("score", models.IntegerField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "question_id",
                    models.IntegerField(blank=True, primary_key=True, serialize=False),
                ),
                ("exam_title", models.CharField(max_length=255)),
                ("question", models.TextField()),
                ("option_a", models.CharField(max_length=255)),
                ("option_b", models.CharField(max_length=255)),
                ("option_c", models.CharField(max_length=255)),
                ("option_d", models.CharField(max_length=255)),
                ("correct_answer", models.CharField(max_length=255)),
                ("marks", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "result_id",
                    models.IntegerField(blank=True, primary_key=True, serialize=False),
                ),
                ("student_name", models.CharField(max_length=255)),
                ("exam_title", models.CharField(max_length=255)),
                ("total_marks", models.IntegerField()),
                ("obtained_marks", models.IntegerField()),
                ("percentage", models.FloatField()),
                ("result_status", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "student_id",
                    models.IntegerField(blank=True, primary_key=True, serialize=False),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("college", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
    ]
